import Head from 'next/head'
import Typewriter from 'typewriter-effect';

import {BsFillMoonStarsFill} from "react-icons/bs"
import {AiFillLinkedin,AiFillGithub} from "react-icons/ai"
import Image from 'next/image'
import  maq from "../public/maq.png"
import da from "../public/da.jpg"
import aicf from "../public/aicf.png"
import cbse from "../public/cbse.jpg"
import gls from "../public/gls.jpg"
import img from "../public/img.png"
import sortipl from "../public/sortipl.jpg"
import guesselo from "../public/guesselo.jpg"
import timetable from "../public/timetable.png"
// import casinowar from "../public/casinowar.jpg"
import casinowar1 from "../public/casinowar1.jpg"
import {useState} from 'react'
export default function Home() {
  const [dark,setDark]=useState(false);
  return (
    <div className={dark?"dark":""}>

      <Head>
        <title>Kabir Kanjani Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-teal-600'>Kabir Portfolio</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={()=>{setDark(!dark)}} className='cursor-pointer dark:text-white'/></li>
              <li><a href="https://drive.google.com/file/d/1gJ4nCXC7Oou35C7fGRGNAyJCYeFVd5lN/view?usp=sharing" className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Resume</a></li>
              <li></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
              <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>
                Kabir Kanjani
                </h2>
              <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>


              <Typewriter
        options={{
          strings: ['Developer', 'Software Engineer'],
          autoStart: true,
          loop: true,
        }}
      />


              </h3>
              <p className='text-md py-5 dark:text-white  leading-8 text-gray-800 md:text-xl mx-w-lg mx-auto'></p>
          </div>
          
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>            
            <a href="https://www.linkedin.com/in/kanjani-kabir-4b6070162/" target="_blank"><AiFillLinkedin className='dark:text-white'/></a>
            <a href="https://github.com/KabirKanjani" target="_blank"><AiFillGithub className='dark:text-white'/></a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
          <Image src={img}  alt={''} />
          </div>
          </section>
          <section>
            <div>
            <h3 className='text-lg dark:text-teal-600  font-medium pt-8 pb-2'>Portfolio</h3>
            <p></p>
            </div>
            <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
              <div className='basis-1/3 flex-1 '>
              <a href="https://sortipl.onrender.com/" target="_blank">
                <Image src={sortipl} alt="" className='rounded-lg object-cover' width={'100'} height={'100'} layout="responsive"/>
                <h3 className='text-lg dark:text-white  font-medium pt-8 pb-2  '>SORTIPL</h3>                            
              <p className='text-md py-5 dark:text-white  leading-8 text-gray-800 md:text-xl mx-w-lg mx-auto '>A Website that sorts IPL Highlights on the basis of runs scored by a certain player</p>
              <p className='text-gray-800 py-1 dark:text-white  '>Tech Stack :Java | PHP | BOOTSTRAP | MYSQL</p>              
              </a>
              </div>
              <div className='basis-1/3 flex-1'>
              <a  target="_blank" href="https://guesselo.onrender.com/">
                <Image src={guesselo} alt="" className='rounded-lg object-cover' width={'100'} height={'100'} layout="responsive"/>
                <h3 className='text-lg dark:text-white  font-medium pt-8 pb-2'>Guess Elo</h3>                            
              <p className='text-md py-5 dark:text-white  leading-8 text-gray-800 md:text-xl mx-w-lg mx-auto'>Infamous Chess game where you guess the elo of players by watching their games</p>
              <p className='text-gray-800 py-1 dark:text-white '>Tech Stack :Mongoose | Express | React | Nodejs | </p>              
              </a>
              </div>
              <div className='basis-1/3 flex-1'>
              <a target="_blank" href="https://casinowars.onrender.com/">
                <Image src={casinowar1} alt="" className='rounded-lg object-cover' width={'100'} height={'100'} layout="responsive"/>
                <h3 className='text-lg dark:text-white  font-medium pt-8 pb-2'>Casino War</h3>                            
              <p className='text-md py-5 dark:text-white  leading-8 text-gray-800 md:text-xl mx-w-lg mx-auto'>A popular card game played across the world in casinos</p>
              <p className='text-gray-800 py-1 dark:text-white '>Tech Stack :EJS | Node | Express | Mongoose</p>              
              </a>
              </div>
              <div className='basis-1/3 flex-1'>
              <a target="_blank" href="https://github.com/KabirKanjani/TimeTableSys">
                <Image src={timetable} alt="" className='rounded-lg object-cover' width={'100'} height={'100'} layout="responsive"/>
                <h3 className='text-lg dark:text-white  font-medium pt-8 pb-2'>TimeTable System</h3>                            
              <p className='text-md py-5 dark:text-white  leading-8 text-gray-800 md:text-xl mx-w-lg mx-auto'>TimeTable System to simulate the daily system of making timetable and making the process easier and automated</p>
              <p className='text-gray-800 py-1 dark:text-white '>Tech Stack :Java | Servlet | JSP | PostgreSQL</p>              
              </a>
              </div>

            </div>
          </section>

          <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-teal-600">Professional Experience</h3>
            <p className='text-md py-2 leading-8 text-gray-80'></p>
            <p className='text-md py-2 leading-8 text-gray-80'></p>
          </div>
          <div className='lg:flex gap-10'>
          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
          <center><Image src={maq} alt="" width={100} height={100}/></center>
              <h3 className='text-lg dark:text-white  font-medium pt-8 pb-2'>Associate Software Engineer Intern</h3>              
              <h4 className='text-md dark:text-white  py-5 leading-8 text-gray-800 md:text-xl mx-w-lg mx-auto'>MAQ Software</h4>
              <p className='text-gray-800 py-1 dark:text-white '>05/2022 – 07/2022 | Mumbai</p>
              <p className='text-md py-5 dark:text-white  leading-8 text-gray-800 md:text-xl mx-w-lg mx-auto'>
                A wonderful learning experience and I got to
                work with diverse technologies like
                Python,Azure Functions, and PowerAutomate
                Flow and created APIs to automate data
                between powerApps and Azure Github.              
              </p>              
            
            </div>
          <div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <center><Image className="" src={aicf} alt="" width={100} height={100}/></center>
              <h3 className='text-lg dark:text-white  font-medium pt-8 pb-2'>Volunteer for Chess Olympiad</h3>              
              <h4 className='text-md dark:text-white  py-5 leading-8 text-gray-800 md:text-xl mx-w-lg mx-auto'>All India Chess Federation</h4>
              <p className='text-gray-800 py-1 dark:text-white '>07/2022 – 08/2022 | Chennai</p>
              <p className='text-md py-5 dark:text-white  leading-8 text-gray-800 md:text-xl mx-w-lg mx-auto'>
              Once in a lifetime experience to be a part of the
              Chess Olympiad and work around all the chess
              fanatics and be a part of this grand event.     
              </p>              
            </div>
          </div>
          </div>

          <div>
            <h3 className="text-3xl py-1 dark:text-teal-600">Education</h3>
            <p className='text-md py-2 leading-8 text-gray-80'></p>
            <p className='text-md py-2 leading-8 text-gray-80'></p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <center><Image src={da} className="" alt="" width={100} height={100}/></center>
              <h3 className='text-lg dark:text-white  font-medium pt-8 pb-2'>Masters of Science in IT</h3>              
              <h4 className='text-md dark:text-white  py-5 leading-8 text-gray-800 md:text-xl mx-w-lg mx-auto'>Dhirubhai AmbaniInstitute ofInformation and Communication Technology (DA-IICT)</h4>
              <p className='text-gray-800 py-1 dark:text-white '>08/2021 – present | Gandhinagar</p>
              <p className='text-gray-800 py-1 dark:text-white '>CPI-8.3</p>              
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <center><Image src={gls} alt="" className='center' width={100} height={100}/></center>
              <h3 className='text-lg dark:text-white  font-medium pt-8 pb-2'>Bachelors of Science in IT</h3>              
              <h4 className='text-md dark:text-white  py-5 leading-8 text-gray-800 md:text-xl mx-w-lg mx-auto'>Faculty of Computer Applications and Information Technology ,GLS University</h4>
              <p className='text-gray-800 py-1 dark:text-white '>07/2018 – 07/2021 | Ahmedabad</p>
              <p className='text-gray-800 py-1 dark:text-white '>CPI-9.37</p>              
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <center><Image src={cbse} alt="" width={100} height={100}/></center>
              <h3 className='text-lg dark:text-white  font-medium pt-8 pb-2'>Secondary & Primary Education</h3>              
            
              <p className='text-gray-800 py-1 dark:text-white '>12th : 79.2%(CBSE)</p>
              <p className='text-gray-800 py-1 dark:text-white '>10th :72%(CBSE)</p>              
            </div>

          </div>


          </section>
      </main>
    </div>
  )
}
